[package]
name = "aliyundrive-webdav"
version = "0.1.10"
edition = "2018"
description = "WebDAV server for AliyunDrive"
license = "MIT"
homepage = "https://github.com/messense/aliyundrive-webdav"
repository = "https://github.com/messense/aliyundrive-webdav.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
async-recursion = "0.3.2"
bytes = "1.0.1"
futures-util = "0.3.16"
headers = "0.3.4"
hyper = { version = "0.14.11", features = ["server"] }
moka = { version = "0.5.1", features = ["future"] }
percent-encoding = "1.0"
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls", "gzip"] }
serde = { version = "1.0.127", features = ["derive"] }
structopt = "0.3.22"
time = { version = "0.3.1", features = ["formatting", "parsing"] }
tokio = { version = "1.10.0", features = ["rt-multi-thread", "io-util", "net", "time", "sync", "macros", "parking_lot"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
url = "2.2.2"
webdav-handler = { version = "0.2.0", default-features = false, features = ["hyper"] }

[patch.crates-io]
webdav-handler = { git = "https://github.com/messense/webdav-handler-rs.git", branch = "aliyundrive" }

[profile.release]
lto = true
opt-level = "z"  # Optimize for size
