[package]
name = "aliyundrive-webdav"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.6"
log = "0.4.14"
pretty_env_logger = "0.4.0"
webdav-handler = { version = "0.2.0", features = ["actix-compat"] }
