blank_issues_enabled: true
contact_links:
  - name: â“ æé—®
    url: https://github.com/messense/aliyundrive-webdav/discussions/categories/q-a
    about: ä¸€èˆ¬ä½¿ç”¨é—®é¢˜è¯·åœ¨è®¨è®ºåŒºæé—®
  - name: ğŸ’¡ æƒ³æ³•åˆ†äº«
    url: https://github.com/messense/aliyundrive-webdav/discussions/categories/ideas
    about: æœ‰åŠŸèƒ½å»ºè®®ã€æƒ³æ³•å¯ä»¥åœ¨è®¨è®ºåŒºå¼€è´´
